# Generated by Django 5.2 on 2025-05-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietary_preferences', models.CharField(max_length=255)),
                ('fitness_goal', models.CharField(max_length=255)),
                ('lifestyle_factor', models.CharField(max_length=255)),
                ('dietary_restrictions', models.CharField(blank=True, max_length=255)),
                ('health_condition', models.CharField(blank=True, max_length=255)),
                ('your_query', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
