# Generated by Django 5.2.2 on 2025-06-05 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrecommendation',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='userrecommendation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='userrecommendation',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='userrecommendation',
            name='lifestyle',
        ),
        migrations.RemoveField(
            model_name='userrecommendation',
            name='preference',
        ),
        migrations.RemoveField(
            model_name='userrecommendation',
            name='query',
        ),
        migrations.RemoveField(
            model_name='userrecommendation',
            name='restriction',
        ),
        migrations.AddField(
            model_name='userrecommendation',
            name='dietary_preferences',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userrecommendation',
            name='dietary_restrictions',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userrecommendation',
            name='fitness_goal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userrecommendation',
            name='health_condition',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userrecommendation',
            name='lifestyle_factor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userrecommendation',
            name='your_query',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userrecommendation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
